# Generated by Django 5.1.4 on 2024-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madcap_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_entree',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
