# Generated by Django 5.1.5 on 2025-02-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madcap_app', '0004_alter_avis_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
