# Generated by Django 5.1.5 on 2025-03-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madcap_app', '0006_alter_member_date_entree'),
        ('madcap_app', '0007_rename_date_entree_member_annee_adhesion'),
    ]

    operations = [
    ]
