# Generated by Django 5.1.5 on 2025-03-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madcap_app', '0004_alter_member_options_alter_member_phone_and_more'),
        ('madcap_app', '0008_merge_20250317_1603'),
    ]

    operations = [
    ]
